<div class="card mb-3">
    <h5 class="card-header">About the Buggy Alumni Association</h5>
    <div class="card-body">
      <p>We were founded in 2008 to unite and connect alumni across teams and eras, and to support the coolest sport we know. Join us! We're open to everyone: current students, Pittsburgh locals, enthusiasts of any kind.</p>
      <a href="/about" class="btn btn-primary">Learn More</a>
    </div>
</div>

<div class="card mb-3">
    <h5 class="card-header">About Buggy</h5>
    <div class="card-body">
      <p>Buggy (also called "Sweepstakes") is a unique race that has been held on and behind the Carnegie Mellon University campus during the spring carnival since 1920. It is part uphill relay race (in which the baton is a vehicle and driver pushed by runners), and part downhill gravity racing with exciting sharp turns and speeds up to 40mph.</p>
      <a href="/reference" class="btn btn-primary">Learn More</a>
    </div>
</div>