<h1>Contribute</h1>

<p>Please use one of the forms below to submit addition or corrections to the data we've got. It's just fine to submit multiple related pieces of information at once (e.g. the build dates of all your org's buggies). If you have a large quantity of data, or if you find it easier, you can also e-mail information to <a href="mailto:data@cmubuggy.org">data@cmubuggy.org</a>.</p>

<p>
  In an effort to make it faster for us to import new data, we have added a couple of standardized forms for specific types of data:
  <ul>
    <li><a href="https://spreadsheets.google.com/viewform?hl=en&formkey=cHJrT3JoWXZvNDRlVFJTSjlCZWE4ZXc6MA..">Raceday Data</a> - pushers, drivers, buggies and their times and places</li>
    <li><a href="https://spreadsheets.google.com/viewform?hl=en&formkey=cHJrT3JoWXZvNDRlOElXNjRoVllOT2c6MA..">Organization Data</a> - mechanics, chairmen, sweepstakes and other non-pushing, non-driving participants</li>
    <li><a href="https://spreadsheets.google.com/viewform?hl=en&formkey=cHJrT3JoWXZvNDRkLTZHc1RTcGE0TkE6MA..">Buggy Data</a> - buggies and their years, pictures, awards</li>
  </ul>
</p>
