<h1>The History of Buggy</h1>

<p>One of the Buggy Alumni Association's primary goals is to act as a repository for buggy history. Check out the links above to explore the historical information we have collected.</p>

<p>If you prefer a written summary, check out our <a href="/news/2019/09/100-years-of-buggy-history-intro-and-1920/">100 Years of Buggy</a> series.

<p>We know our data is incomplete and sometimes inaccurate.  If you have something important to share, send an email to <a href="mailto:data@cmubuggy.org">data@cmubuggy.org</a>.</p>
