<h1>The History of Buggy</h1>

<p>One of the Buggy Alumni Association's primary goals is to act as a repository for buggy history. Check out the links above to explore the historical information we have collected.</p>

<p>We are hoping to finish a system to allow efficient contributions of new data and corrections sometime soon. In the mean time, if you have something important to share, send an email to <a href="mailto:admin@cmubuggy.org">admin@cmubuggy.org</a>.</p>
