<div class="container">
 <div class="row">
   <div class="col">
     <div class="card border-primary my-4 p-3">
     <p class="card-text">One of the Buggy Alumni Association's primary goals is to act as a repository for Buggy history.
     We've worked hard to collect both historical records and stories of Sweepstakes through the years.  Here's what we
     have collected.
     </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/news/2019/09/100-years-of-buggy-history-intro-and-1920/">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-red)"></i>
          <i class="fas fa-scroll fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          Our <a href="/news/2019/09/100-years-of-buggy-history-intro-and-1920/">100 Years of Buggy</a> blog series
        </div>
     </div>
   </div>
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/<?php echo($RACEDAY_URL_PART); ?>">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-yellow)"></i>
          <i class="fas fa-trophy fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          <a href="/history/<?php echo($RACEDAY_URL_PART); ?>">Race Results</a> for every year
        </div>
      </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/org">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-blue)"></i>
          <i class="fas fa-users fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          Every <a href="/history/org">Buggy Organization</a>, past or present
        </div>
     </div>
   </div>
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/award">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-green)"></i>
          <i class="fas fa-award fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          <a href="/history/award">Awards</a> for the Design Competition and Organizations
        </div>
      </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/buggy">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-yellow)"></i>
          <i class="fas fa-wrench fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          Every <a href="/history/buggy">buggy</a> we have identified
        </div>
     </div>
   </div>
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/person">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-red)"></i>
          <i class="fas fa-running fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          <a href="/history/person">Search people</a> to see the races they were in.
        </div>
      </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/buggybook">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-green)"></i>
          <i class="fas fa-book fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          Past <a href="/history/buggybook">Buggy Books</a>
        </div>
     </div>
   </div>
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/sweepstakes">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-blue)"></i>
          <i class="fas fa-user-friends fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          <a href="/history/sweepstakes">Sweepstakes Committees</a> and the <a href="/history/baa">BAA Boards</a>
        </div>
      </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/history/video">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-red)"></i>
          <i class="fas fa-video fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          <a href="/history/video">Videos</a> of previous <?php echo($RACEDAY_WORD."s"); ?>
        </div>
     </div>
   </div>
   <div class="col">
      <div class="d-flex mb-3"><div class="flex-shrink-0">
        <a href="/news/history/raceday-previews">
         <span class="fa-layers fa-fw fa-2x mr-2">
          <i class="fas fa-square" style="color: var(--bs-yellow)"></i>
          <i class="fas fa-binoculars fa-inverse" data-fa-transform="shrink-8"></i>
         </span>
        </a>
        </div><div class="flex-grow-1 pl-3">
          Past <a href="/news/history/raceday-previews"><?php echo($RACEDAY_WORD); ?> Previews and Spotting Guides</a>
        </div>
     </div>
   </div>
 </div>
 <div class="row">
   <div class="col">
     <div class="card border-secondary m-3">
      <div class="card-header">Something Wrong or Missing?</div>
      <div class="card-body text-secondary">
       <p class="card-text">We know our data is incomplete and sometimes inaccurate.  If you have something important to share, send an email to <a href="mailto:data@cmubuggy.org">data@cmubuggy.org</a>.</p>
      </div>
     </div>
   </div>
 </div>
</div>