	<span style="font-size:1.3em;">Fantasy buggy is just like other fantasy sports: you pick a variety of contestants in the actual sport to compose your fantasy team.  The better your picks do in real life, the better your fantasy team does.  If your picks are the best you'll have $250 in your pocket to fund your trip to Carnival this year!</span><br />
	<br />
	Ready for some details?  Here they come. (Details are subject to change until the game opens)
	<h4>Timeline</h4>
	<ul class="list">
		<li>Fri Oct 21, 8:00am : Game open to entries</li>
		<li>Fri Nov 4, 11:59pm : All entries must be in</li>
		<li>Sun Nov 6, 7:00-9:00am: Rolls and times are collected</li>
		<li>Soon thereafter: Winner is announced</li>
	</ul>
	<h4>Descriptives</h4>
	<ul class="list">
		<li>40-75 rolls on a fall day of freerolls</li>
		<li>25 Potential Buggies</li>
		<li>7 orgs + [SN and/or Delta Force]</li>
	</ul>
	<h4>Basics</h4>
	<ul class="list">
		<li>Pick 4 freerolls and 4 back hills</li>
		<li>Each pick specifies Org-Roll-Buggy-Segment  (e.g. SigEp-Roll2-Barracuda-Freeroll)</li>
		<li>Must make 1 and only 1 pick from each org</li>
		<li>1 entry per person</li>
	</ul>
	<h4>Scoring</h4>
	<ul class="list">
		<li>Score = total of 4 freeroll times + 4 back hill times</li>
		<li>Segments that don't happen (the buggy isn't out or doesn't roll the specified roll) are given that org's worst time +1 second</li>
		<li>Spins or stops are given the overall worst time + 2 seconds</li>
		<li>Women's freerolls are given their time - 3 seconds</li>
		<li>Women's backhills are given their time - 6 seconds</li>
		<li>Tie-breaker: closest guess on winning men's hill 2->finish time</li>
	</ul>
	<h3>Let's do it!</h3>
	<table summary="" style="width=500px; margin:0 auto;">
		<tr>
			<td style="width:250px;">
				<div class="button"><a href="/membership">Step 1. Become a Member</a></div>
			</td>
			<td style="width:250px">
				<div class="button"><a href="/fantasy/enter">Step 2. Make your Picks</a></div>
			</td>
		</tr>
		<tr>
			<td style="width:250px; padding:32px 0 0 0;">This isn't actually required, but it would mean a lot.  Any gift $1 or larger makes you a member! You're not going to get better odds on a $250 prize anywhere else.</td>
			<td style="width:250px;">The game is open, make your picks!</td>
		</tr>
	</table>
	<h4>Fine Print</h4>
	<ul class="list">
		<li>Freeroll and Back Hills are timed according to Sweepstakes' timing plans for the weekend.  I assume freeroll = crosswalk -> window 0 and backhills = window 0 -> finish</li>
		<li>Roll values will be restricted to 1-3.  It's possible 4th rolls will happen, but unlikely a 4th roll will be completed for all orgs.</li>
		<li>If rolls are rained out on Oct 29th, times from the next day of rolls that do occur will be used for the game.</li>
		<li>When making a pick, roll X refers to the Xth time that org has sent buggies down the hill.  If SDC rolls only Rage on their first roll of the day, and then sends all buggies the second time SDC comes up in the roll order, that is Roll 2 for each of their buggies.</li>
		<li>If the timers fail to record a time for any segment, the time awarded will be the median time on that segment by that buggy.  If the buggy had no other rolls, the median for the org will be used.  If the org had no other rolls, the median for all orgs will be used.</li>
		<li>Delta Force and SN will be lumped together into a single org for the purpose of the game.  We're not sure either will roll.  Both have only one buggy, so no buggy selection is necessary.  If both orgs roll, the times from the faster org for each roll will be used for scoring. If neither org rolls, those picks will be dropped from everyone's entry.</li>
		<li>The BAA judges may throw out a freeroll or backhills time that is more than 2 SD slower than the median freeroll / backhill if something funny happened or it seems like they were going intentionally slow for some reason.  If this is necessary, the segment will be scored as if it did not occur (i.e. worst remaining time + 1 second)</li>
		<li>Women's freerolls are those that follow a female hill 2.  Women's backhills are those with 3 female pushers.  Any co-ed backhills entry will be scored as a Men's entry.</li>
		<li>Prize will be paid by check or pre-paid debit card or something and doesn't actually have to be used for travel, but we do hope you'll come to carnival!</li>
		<li>Current BAA committee members may enter but may not win the prize.</li>
	</ul>
