<ul class="tabs">
	<li><a id="t1" href="#about">About</a></li>
	<li><a id="t2" href="#people">People</a></li>
	<li><a id="t3" href="#finances">Finances</a></li>	
	<!--<li><a id="t4" href="#getinvolved">Get Involved</a></li>-->
	<li><a id="t4" href="#website">This Website</a></li>
</ul>

<div class="panes">
	<div class="pane">
		<h3>Founding Story</h3>
		The Carnegie Mellon Buggy Alumni Association was founded in the summer of 2008 after it became clear that there was both a need and an interest in an organization centered around buggy for all members of the buggy world, past and present.
		<h3>Mission</h3>
		The founding members defined 5 goals to guide the organization's efforts:
		<ol>
			<li>Preserve and make accessible the history of the sport</li>
			<li>Provide a channel by which alumni can remain connected to and support the sport</li>
			<li>Support and improve undergraduate participation</li>
			<li>Improve relations and raise interest in the greater Pittsburgh community</li>
			<li>Unite alumni across organizations</li>						
		</ol>
		<h3>What are we?</h3>
		We are an Alumni Interest Group from Carnegie Mellon University.  That means we are non-profit, officially recognized by Carnegie Mellon, and generally based in Pittsburgh.  We are open to anyone who is interested in buggy; you need not be a "Buggy Alumni" to get involved.  We work with plenty of current CMU students and other buggy fans.   
	</div>		
	<div class="pane">
		Members of the Buggy Alumni Association board are elected to 2 year terms by the rest of the BAA community.  Ideally, the terms are staggered so that 2 positions are elected each year.<br />
		<br />
		<table class="data">
			<tr><th colspan="2">Current leaders</th></tr>
			<tr><td>Chairman</td><td><a href="/history/person/1104">Janice Golenbock</a></td></tr>	
			<tr><td>Assistant Chairman</td><td><a href="#">Shafeeq Sinnamohideen</a></td></tr>
			<tr><td>Head Mechanic</td><td><a href="/history/person/1147">Sam Swift</a></td></tr>
			<tr><td>Treasurer</td><td><a href="/history/person/1531">Chris Stengel</a></td></tr>
		</table>
		<br />
		<table class="data">
			<tr><th colspan="2">More super important people</th></tr>
			<tr><td>Chairman 2008-2010</td><td>Carsen Kline</td></tr>
			<tr><td>Assistant Chairman 2008-2010</td><td>Aiton Goldman</td></tr>		
			<tr><td>Advisor / Historian</td><td><a href="/history/person/1442">Tom Wood</a></td></tr>
			<tr><td>Enthusiasm / Web</td><td><a href="/history/person/542">Adam McCue</a></td></tr>
			<tr><td>Productive enthusiasm</td><td><a href="#">Abby Sullivan</a></td></tr>
		</table>
	</div>
	<!--
	<div class="pane">
		The Buggy Alumni Association's projects are funded by donations from its members and so we believe strongly in transparency 
	</div>
	-->
	<div class="pane">
		The Buggy Alumni Association is the product of efforts by a large number of buggy alumni who contributed small and large amounts of their time, expertise, and resources to do the things we thought would be cool for buggy.<br />
		<br />
		If you have time, expertise, or resources you can help further the effort.  Don't assume we know what we're doing and have it covered. If you see something that could be done, let us know and let's make it happen.  Post your idea in the forum, or email committee@cmubuggy.org<br />
		<br />
		Some areas are always in need of help:
		<ul>
			<li><a href="http://github.com/swiftsam/cmubuggy.org"><b>Web Development</b></a> - Document bugs, contribute code, invent entirely new functions.  You can do all the above through our github site.</li>
			<li><a href="/news"><b>News</b></a> - We try to be the best source for all buggy news.  This means writing a "Rolls Report" each weekend of rolls as well as covering anything else that happens.  Want to write about buggy?  We'd be happy to have you on the News team.</li>
			<li><a href="/gallery"><b>Pictures</b></a> - Current pictures of freerolls and raceday keep the site current, and old pictures give the site historical depth.  We want both.  Scanning and uploading are time consuming but very much appreciated.</li>
			<li><a href="/reference"><b>Reference</b></a> - the reference wiki could cover 10 times as many topics as it does currently.  Find a gap in the knowledge and fill it.  New teams and new fans will thank you.	
		</ul>
	</div>
	<div class="pane">
		cmubuggy.org was first launched in October of 2008.  The majority of the original code and design were by Sam Swift (samswift@cmubuggy.org).
		Adam McCue and Scott Ziolko helped considerably with data structure and population of the history section.  Refinements were made in an un-managed and as-needed basis for 2+ years.<br />
		<br />
		<a href="http://github.com/swiftsam/cmubuggy.org"><img style="float:left; margin:0 10px 0 0" alt="github" class="default" height="45" src="https://a248.e.akamai.net/assets.github.com/images/modules/header/logov6.png"></a>
		The first major overhaul of the site was "completed" just in time for raceday 2011.  This version of the site was committed to a github repository in the summer of 2011 to allow greater community involvement in coding the site.  Please, if you're reading this, do not hesitate to get involved.<br />
		The github issue tracker is also the best place to point out bugs and suggest improvements or new features.<br />
		<br />
		The site is built around a number of 3rd party platforms and tools.  They are all free, open-source php projects and each has been super useful in making this website as useful as it is to buggy fans so they deserve some recognition:<br />
		<br />
		<ul>
			<li>Data Objects: all custom data objects make use of the <a href="http://www.phpobjectgenerator.com/">PHP Object Generator library</a></li>
			<li>Forum: /forum runs <a href="http://www.phpbb.com/">phpBB</a></li>
			<li>Gallery: /gallery runs <a href="http://gallery.menalto.com/">gallery3</a></li>
			<li>Wiki: /reference runs <a href="http://www.mediawiki.org/">Mediawiki</a></li>
			<li>News: /news runs <a href="http://wordpress.org/">Wordpress</a></li>
		 </ul>
	</div>
</div>
