<ul class="tabs">
	<li><a id="t1" href="#about">About</a></li>
	<li><a id="t2" href="#people">People</a></li>
	<li><a id="t3" href="#finances">Finances</a></li>
	<li><a id="t4" href="#getinvolved">Get Involved</a></li>
</ul>

<div class="panes">
	<div class="pane">
		<h3>Founding Story</h3>
		The Carnegie Mellon Buggy Alumni Association was founded in the summer of 2008 after it became clear that there was both a need and an interest in an organization centered around buggy for all members of the buggy world, past and present.
		<h3>Mission</h3>
		The founding members defined 5 goals to guide the organization's efforts:
		<ol>
			<li>Preserve and make accessible the history of the sport</li>
			<li>Provide a channel by which alumni can remain connected to and support the sport</li>
			<li>Support and improve undergraduate participation</li>
			<li>Improve relations and raise interest in the greater Pittsburgh community</li>
			<li>Unite alumni across organizations</li>						
		</ol>
		<h3>What are we?</h3>
		We are an Alumni Interest Group
	</div>		
	<div class="pane">
		<div class="title">People</div>
		<table class="data">
			<tr><th colspan="2">"Official" positions</th></tr>
			<tr><td>Chairman</td><td><a href="/history/person/1104">Janice Golenbock</a></td></tr>	
			<tr><td>Vice President</td><td><a href="#">Shafeeq Sinnamohideen</a></td></tr>
			<tr><td>Head Mechanic</td><td><a href="/history/person/1147">Sam Swift</a></td></tr>
			<tr><td>Treasurer</td><td><a href="/history/person/1531">Chris Stengel</a></td></tr>
			<tr><th colspan="2">More super important people</th></tr>	
			<tr><td>Advisor / Historian</td><td><a href="/history/person/1442">Tom Wood</a></td></tr>
			<tr><td>Enthusiasm / Web</td><td><a href="/history/person/542">Adam McCue</a></td></tr>
			<tr><td>Productive enthusiasm</td><td><a href="#">Abby Sullivan</a></td></tr>
		</table>
	</div>
	<div class="pane">
		<table class="data">
			
		</table>	
	</div>
	<div class="pane">
		<table class="data">
			
		</table>	
	</div>
</div>
