<ul class="tabs">
	<li><a id="t1" href="#basics">The Basics</a></li>
	<li><a id="t2" href="#accomplishments">Accomplishments</a></li>
	<li><a id="t3" href="#people">People</a></li>
	<!--<li><a id="t3" href="#finances">Finances</a></li>-->
	<li><a id="t4" href="#getinvolved">Get Involved</a></li>
	<li><a id="t5" href="#website">This Website</a></li>
</ul>

<div class="panes">
	<div class="pane">
		<h3>Founding Story</h3>
		The Carnegie Mellon Buggy Alumni Association was founded in the summer of 2008 after it became clear that there was both a need and an interest in an organization centered around buggy for all members of the buggy world, past and present.
		<h3>Mission</h3>
		The founding members defined 5 goals to guide the organization's efforts:
		<ol>
			<li>Preserve and make accessible the history of the sport</li>
			<li>Provide a channel by which alumni can remain connected to and support the sport</li>
			<li>Support and improve undergraduate participation</li>
			<li>Improve relations and raise interest in the greater Pittsburgh community</li>
			<li>Unite alumni across organizations</li>
		</ol>
		<h3>What are we?</h3>
		We are an Alumni Interest Group from Carnegie Mellon University.  That means we are non-profit, officially recognized by Carnegie Mellon, and generally based in Pittsburgh.  We are open to anyone who is interested in buggy; you need not be a "Buggy Alumni" to get involved.  We work with plenty of current CMU students and other buggy fans.
	</div>
	<div class="pane">
		Having a club is all well and good, but what have we done?<br />
		<br />
		<h4>This website</h4>
		You're here, so no need to spend much time describing this one, but we're pretty proud of it and hope you like it.  It is central to our mission(s) though, that current buggy folks, alumni, and fans can gather to follow, discuss, and support the sport online.<br />
		<br />
		The website itself is cool, but the content it has allowed us to gather is a bigger part of what this group has been able to accomplish.  Our history section is the most complete record of race results and participants that exists.  Our gallery is goes way back.  Our reference section is ... off to a good start. All of the above is thanks to the many contributions from members.
		<h4>Publications</h4>
		Our schedule of publications has changed a bit year to year, but each has been a pretty awesome summary of the current state of buggy for our members near and far.  Lucky you, you can still download them here:
		<ul style="margin-left:10px;">
			<li><b>2009</b>
				<ul class="list">
					<li><a href="/files/FallWrapup2009.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Fall Wrapup</li>
					<li><a href="/files/RacedayPreview2009.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Preview</a></li>
					<li><a href="/files/RacedayGuide2009Prelims.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Guide (Prelims)</a></li>
					<li><a href="/files/RacedayGuide2009Finals.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Guide (Finals)</a></li>
					<li><a href="/files/RacedayWrapup2009.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Wrapup</a></li>
				</ul>
			</li>
			<li><b>2010</b>
				<ul class="list">
					<li><a href="/files/Newsletter20100106.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">January Newsletter</a></li>
					<li><a href="/files/RacedayPreview2010.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Preview</a></li>
					<li><a href="/files/RacedayGuide2010Prelims.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Guide (Prelims)</a></li>
				</ul>
			</li>
			<li><b>2011</b>
				<ul class="list">
					<li><a href="/files/RacedayPreview2011.pdf" target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Preview</a></li>
					<li><a href="/files/RacedayGuide2011.pdf"  target="_blank" onclick="_gaq.push(['_trackEvent','Download','PDF',this.href]);">Raceday Guide</a></li>
				</ul>
			</li>
		</ul>
		<h4>Raceday video archive</h4>
		In 2011, the BAA unveiled an archive of buggy videos with an initial collection of over 200 videos from the 1950's up to complete coverage of 2003-2010 racedays.  Previously the fine coverage produced by cmuTV was unavailable online.  This project was costless, but many hours went into transcoding, sorting, and uploading videos to youtube.
		<a href="/gallery/2009-2010/prelims/finishline" ><img style="float:right" src="/gallery/var/thumbs/2009-2010/prelims/finishline/Result%202-w2-SDCB-SpiritB-CIAB.jpg?m=1302290137" alt="Timing system" ></a>
		<h4>Raceday timing system upgrades</h4>
		In 2009, the company that had been hired to run buggy timing for years showed up short-staffed so BAA members filled in in critical roles.  What we saw gave us enough information to confirm that buggy was due for an upgrade in the sophistication of its timing system.  We worked with sweepstakes in the 2009-2010 season and made it happen.<br />
		<br />
		The BAA contributed $1,200 to sweepstakes for raceday 2010 to enable a month-long rental of a FinishLynx digital photofinish and timing system to fully test and vet the system before raceday.  Ongoing rental prices are within Sweepstakes' normal budget.<br />
		<br />
		For the 2010 and 2011 races, the system was operated by BAA members.<br />
		<br />
		More info on the timing system project as it developed here in the news section:<br />
		<ul class="list">
			<li><a href="/news/2010/02/raceday-timing-system-upgrade/" >Raceday timing system upgrade (Feb 18, 2010)</a></li>
			<li><a href="/news/2010/03/timing-system-in-hand-and-working/" >Timing System in hand and working (March 17, 2010)</a></li>
			<li><a href="/news/2010/03/timing-system-test-at-rolls-a-success/" >Timing System test at rolls a success (March 27, 2010)</a></li>
		</ul>
		<a href="/gallery/2008-2009/Finals/atmosphere/DSC_0255" ><img style="float:right" src="/gallery/var/thumbs/2008-2009/Finals/atmosphere/DSC_0255.JPG?m=1302290126" alt="Timing system" ></a>
		<h4>Jumbotrons</h4>
		One of the original pie-in-the-sky project ideas for the BAA was to get a jumbotron for raceday.  The geography of the course makes it tough to follow everything that's going on and besides it would just be awesome.<br />
		<br />
		In 2009, a CMU spin-off provided a jumbotron at no cost to Sweepstakes and proved it was a valuable addition to raceday.  In 2010 and 2011, the BAA contributed $1000 to subsidize the cost of not one, but two jumbotrons.  Money was raised by running the now-annual Lead Truck auction in which bidders compete to ride in the lead truck during the races.<br />
		<br />
		More info on the jumbotron and lead truck auction projects:<br />
		<ul class="list">
			<li><a href="/news/2010/03/lead-truck-auction-2010-2-jumbotrons/" >Lead Truck Auction 2010 -> 2 Jumbotrons! (Mar 26, 2010)</a></li>
			<li><a href="/news/2010/03/timing-system-in-hand-and-working/" >Timing System in hand and working (March 17, 2010)</a></li>
			<li><a href="/news/2010/03/timing-system-test-at-rolls-a-success/" >Timing System test at rolls a success (March 27, 2010)</a></li>
		</ul>

	</div>
	<div class="pane">
		Members of the Buggy Alumni Association board are elected to 2 year terms by the rest of the BAA community.  Ideally, the terms are staggered so that 2 positions are elected each year.<br />
		<br />
		<table class="data">
			<tr><th colspan="2">Current leaders</th></tr>
			<tr><td>Chairman</td><td>Ben Matzke</td></tr>
			<tr><td>Assistant Chairman</td><td>Jeremy Tuttle</td></tr>
			<tr><td>Head Mechanic</td><td><a href="/history/person/1147">Sam Swift</a></td></tr>
			<tr><td>Head Reporter</td><td>Natalie McGuier</td></tr>
			<tr><td>Communications Chair</td><td>Aileen Dinin</td></tr>
			<tr><td>Treasurer</td><td>Daniel Becerra</td></tr>
			<tr><td>Design / Content</td><td>Connor Hayes</td></tr>
		</table>
		<br />
		<table class="data">
			<tr><th colspan="2">More super important people</th></tr>
			<tr><td>Chairman 2008-2010</td><td>Carsen Kline</td></tr>
			<tr><td>Assistant Chairman 2008-2010</td><td>Aiton Goldman</td></tr>
			<tr><td>Advisor / Historian</td><td><a href="/history/person/1442">Tom Wood</a></td></tr>
			<tr><td>Enthusiasm / Web</td><td><a href="/history/person/542">Adam McCue</a></td></tr>
			<tr><td>Productive enthusiasm</td><td><a href="#">Abby Sullivan</a></td></tr>
		</table>
		<br />
		Of course when it comes to people, it's really all about the supporting members who are listed in the <a href="/membership#roster">membership section</a>.
	</div>
	<!--
	<div class="pane">
		The Buggy Alumni Association's projects are funded by donations from its members and so we believe strongly in transparency
	</div>
	-->
	<div class="pane">
		The Buggy Alumni Association is the product of efforts by a large number of buggy alumni who contributed small and large amounts of their time, expertise, and resources to do the things we thought would be cool for buggy.<br />
		<br />
		If you have time, expertise, or resources you can help further the effort.  Don't assume we know what we're doing and have it covered. If you see something that could be done, let us know and let's make it happen.  Post your idea in the forum, or email committee@cmubuggy.org<br />
		<br />
		Some areas are always in need of help:
		<ul class="list">
			<li><a href="https://github.com/swiftsam/cmubuggy.org"><b>Web Development</b></a> - Document bugs, contribute code, invent entirely new functions.  You can do all the above through our github site.  It's also very helpful if you report any problems you find with the site through the github issues section.</li>
			<li><a href="/news"><b>News</b></a> - We try to be the best source for all buggy news.  This means writing a "Rolls Report" each weekend of rolls as well as covering anything else that happens.  Want to write about buggy?  We'd be happy to have you on the News team.</li>
			<li><a href="/gallery"><b>Pictures</b></a> - Current pictures of freerolls and raceday keep the site current, and old pictures give the site historical depth.  We want both.  Scanning and uploading are time consuming but very much appreciated.</li>
			<li><a href="/reference"><b>Reference</b></a> - the reference wiki could cover 10 times as many topics as it does currently.  Find a gap in the knowledge and fill it.  New teams and new fans will thank you.
			<li><a href="https://reddit.com/r/cmubuggy"><b>Project Zone</b></a> - Check out our "Project Zone" to suggest a new project, vote on, or discuss existing ideas.  This section of the site makes use of the popular site reddit.  Let us know what you think.
		</ul>
	</div>
	<div class="pane">
		cmubuggy.org was first launched in October of 2008.  The majority of the original code and design were by Sam Swift (samswift@cmubuggy.org).
		Adam McCue and Scott Ziolko helped considerably with data structure and population of the history section.  Refinements were made in an un-managed and as-needed basis for 2+ years.<br />
		<br />
		<a href="https://github.com/swiftsam/cmubuggy.org"><img style="float:left; margin:0 10px 0 0" alt="github" class="default" height="45" src="https://a248.e.akamai.net/assets.github.com/images/modules/header/logov6.png"></a>
		The first major overhaul of the site was "completed" just in time for raceday 2011.  This version of the site was committed to a github repository in the summer of 2011 to allow greater community involvement in coding the site.  Please, if you're reading this, do not hesitate to get involved.<br />
		The github issue tracker is also the best place to point out bugs and suggest improvements or new features.<br />
		<br />
		The site is built around a number of 3rd party platforms and tools.  They are all free, open-source php projects and each has been super useful in making this website as useful as it is to buggy fans so they deserve some recognition:<br />
		<br />
		<ul class="list">
			<li>Data Objects: all custom data objects make use of the <a href="http://www.phpobjectgenerator.com/">PHP Object Generator library</a></li>
			<li>Forum: /forum runs <a href="http://www.phpbb.com/">phpBB</a></li>
			<li>Gallery: /gallery runs <a href="http://gallery.menalto.com/">gallery3</a></li>
			<li>Wiki: /reference runs <a href="http://www.mediawiki.org/">Mediawiki</a></li>
			<li>News: /news runs <a href="http://wordpress.org/">Wordpress</a></li>
		 </ul>
	</div>
</div>
