<div class="pane">
		<img style="float:right; margin:15px;" class="aligncenter" title="Lead Truck" src="http://cmubuggy.org/img/news/baaleadtruck.JPG" alt="Lead Truck" width="224" height="149" />				
		<h2>See the WHOLE race this year!</h2>
		We'll be having our 5th annual auction for rides in the official sweepstakes lead truck for each heat of the prelim and final races. Auction winners will ride in the bed of the pickup truck with the head judge, sweepstakes chairman, and other race officials to get the absolute best seat in the house.<br />
		<br />
		The auction is the Buggy Alumni Association's largest source of fund-raising each year, allowing us to pursue our <a style="font-weight:bold;" href="http://cmubuggy.org/about/">mission to support buggy.</a>  Last year's auction allowed us to upgrade the timing technology and help rent jumbotrons for raceday!</a>
		<br />
		<br />
		<div style="text-align:center; margin:15px;">
			<div class="button" style="margin:0 auto; font-size:1.4em;">Bidding starts at 9am Apr 16</div>
		</div>					
		<br />
		The details of the auction go like this:
		<ul>
			<li><br /><b>General</b>
				<ul class="list">
					<li>All heats will be auctioned simultaneously</li>
					<li>The bidding will start at 9am EDT Tuesday April 16th</li>
					<li>Bidding will end at 9pm EDT Wednesday April 17th</li>
					<li>Each heat will have a $10 minimum bid</li>
					<li>The minimum bidding increment is $1</li>
					<li>You may specify a maximum amount you wish to bid for any heat.  The site will automatically increase your bid in $1 increments as needed until your maximum is exceeded by someone else.</li>
					<li>Payment must be received before winners take their rides.  Credit card payment will be available and is strongly preferred.  Cash and Check will also be accepted at the races.</li>
					<li>Lead truck rides are transferable.  If you can't be in town or don't like trucks, feel free to bid on an auction and then tell us who gets to take the ride.  You can also just will it to your organization of choice and we'll let the lucky team pick who gets to ride.</li>
				</ul>
			</li>
			<li><br /><b>Prelim Heat specifics</b>
				<ul>
					<li class="list">If any person wins the auctions for more than one heat, they will have the option of retracting their winning bids for all but the highest priced heat.  If they decide to withdraw their winning bid for one of the lower priced heats, the next highest bidder will become the winner.</li>
				</ul>
			</li>
			<li><br /><b>Finals Heat specifics</b>
				<ul class="list">
					<li>Because the specifics of the finals heats are unknown, bidders will be bidding for the right to have first pick of the finals heats.  Runners up will have 2nd, 3rd pick, etc.</li>
					<li>There will be only two things to bid on for finals: Men's Finals and Women's Finals</li>
					<li>The top 5 bidders for the Men's Finals will have the opportunity to select a heat in order of their bids</li>
					<li>The top 3 bidders for the Women's Finals will have the opportunity to select a heat in order of their bids</li>
					<!--<li>The top 5 bidders for the Exhibition heats will have the opportunity to select a heat in order of their bids</li>-->
					<li>You may not place a bid that is equal to an existing bid</li>
					<li>You may place a bid lower than the current top bid so long as it is higher than the current 5th (Men's) or 3rd (Women's) place bid.</li>
				</ul>
			</li>	
		</ul>
		<br />
		<b><a href="cmubuggy.org/forum/viewtopic.php?f=3&t=412&p=4139">Suggestions, discussion, and requests for clarification can be made in the forum</a></b><br />
		<br />
		We are, of course extremely thankful to sweepstakes for giving us the opportunity to use a spot in the lead truck to create this opportunity and to raise some money so that the Buggy Alumni Association can pursue <b><a href="http://cmubuggy.org/about/">its mission to support buggy</a></b>.<br />
		<br />
		<b>Fine print details</b>
		<ul class="list">
			<li>All winning bids will be considered a gift to the Buggy Alumni Association. We have worked closely with the university to make sure that your gift to the BAA is also credited as a gift to Carnegie Mellon. Be assured that 100% of your gift will go to the Buggy Alumni Association. Also, if you're an alum celebrating a reunion, your gift to the BAA will be counted towards your class totals.</li>
			<li>For tax recognition purposes the donor can only claim their gift amount above the Fair Market Value of the Ride Auction. The fair market value of the Buggy Alumni Association Ride Auction is $10.00. Only the amount of your donation above the fair market value of the EVENT is tax deductible. Please consult your tax advisor for more information.</li>
			<li>If two people specify the same maximum bid, and the auction ends without any higher bids, the person that entered their maximum bid first will be the winner.</li>						
			<li>The end time (9pm EDT Wednesday April 17th) is fixed.  There will be no extensions to allow for last minute bids.  Get your bids in early and make use of the max bid feature!</li>							
			<li>Any heats that get rained out or otherwise cancelled will just void the auction for those heats.  Of course, if winners of cancelled heats want to make their donations anyway, we won't complain.</li>
			<li>Winners should be present at the top of hill 2 at the end of the preceding heat.  Failure to show up in a timely manner will result in forfeiting the ride.  We can't be the cause of any delays, so the Buggy Alumni Association will have to be conservative in our estimation of "timely manner."  Be there!</li>
			<li>The Buggy Alumni Association and Sweepstakes reserve the right to refund donations from and refuse a ride to anyone that is drunk or otherwise unable to safely ride in the back of a truck.</li>
			<li>No rides may violate Pennsylvania's laws concerning riding in a pickup truck.  Basically this means the passenger must be over 18. (<a href="http://www.dmv.state.pa.us/pdotforms/vehicle_code/chapter37.pdf">pdf</a>)</li>
			<li>Sweepstakes also reserves the right to cancel rides and have the us refund donations if they need to for any reason.</li>						
		</ul>
	</div>
