<nav class="navbar navbar-light navbar-expand bg-light mb-3">
  <ul class="navbar-nav flex-wrap">
    <li class="nav-item"><a class="nav-link" href="/live" target="_blank">Live Streaming Broadcast</a></li>
    <li class="nav-item"><a class="nav-link" href="/buzz" target="_blank">Buzz (live chat)</a></li>
  </ul>
</nav>

<iframe src="https://webchat.freenode.net?channels=cmubuggy&uio=Mj10cnVlJjQ9dHJ1ZSYxMT0yMDU80" width="647" height="600"></iframe>
