<div class="pane">
  <h1>Carnival 2018 BAA Event Schedule</h1>
  <table class="data" border="0">
    <tbody>
      <tr>
        <th colspan="2">Prelims Lead Truck Auction</th>
      </tr>
      <tr>
        <td width="180">Open: Mon, April 16 @ 9am</td>
        <td rowspan="2">Bid online on your favorite preliminary heats for your chance at the best buggy viewing experience! Rules and link will be posted in a future news post.</td>
      </tr>
      <tr>
        <td>Close: Wed, April 18 @ 11pm</td>
      </tr>
      <tr>
        <th colspan="2">WRCT Pre-Raceday Broadcast</th>
      </tr>
      <tr>
        <td>Wed 18th @ 8pm</td>
        <td>Tune in to hear current students and locals share their predictions for this year’s races, listen locally on 88.3 fm or online via <a href="http://www.wrct.org">wrct.org</a></td>
      </tr>
      <tr>
        <th colspan="2">Myth’s and Legends of Buggy Panel</th>
      </tr>
      <tr>
        <td>Thurs, April 19 @ 12:30pm</td>
        <td>Taking a page from the Carnival theme this year, a group of panelists across the generations will share their own buggy myths and legends during Design Showcase. Panelists to be announced.</td>
      </tr>
      <tr>
        <th colspan="2">Welcome Back Happy Hour</th>
      </tr>
      <tr>
        <td>Thurs, April 19 @ 7:30pm</td>
        <td><b>*NEW LOCATION*</b> This year, our Welcome Back Happy Hour is moving to Fuel and Fuddle, the newest bar with a buggy! Come hang out with other early arrivals and share your Raceday 2018 predictions.</td>
      </tr>
      <tr>
        <th colspan="2">History of Buggy (‘93 edition) w/ Tom Wood</th>
      </tr>
      <tr>
        <td>Friday, April 20 @ 1:30pm</td>
        <td>Our regular can’t miss event is back as Tom Wood shares a history of buggy focused on the class of ‘93. His talk will be held in the Danforth Conference room in the CUC.</td>
      </tr>
      <tr>
        <th colspan="2">Buggy Meetup and Finals Lead Truck Auction</th>
      </tr>
      <tr>
        <td>Friday, April 20 @ 7:30pm</td>
        <td><strong>*NEW EVENT*</strong> For the first time ever, bid live on the finals heats’ lead truck rides <i>after</i> the heats have been decided, and stick around to share your Raceday experiences at Hough’s taproom, the original bar with a buggy!</td>
      </tr>
    </tbody>
  </table>
</div>
