<h1>Carnival 2018 BAA Event Schedule</h1>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Prelims Lead Truck Auction</h5>
    <h6 class="card-subtitle mb-2 text-muted">Mon, April 16 @ 9am &ndash; Wed, April 18 @ 11pm</h6>
    <p class="card-text">Bid online on your favorite preliminary heats for your chance at the best buggy viewing experience! Rules and link will be posted in a future news post.</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">WRCT Pre-Raceday Broadcast</h5>
    <h6 class="card-subtitle mb-2 text-muted">Wed, April 18th @ 7pm</h6>
    <p class="card-text">Tune in to hear current students and locals share their predictions for this year’s races, listen locally on 88.3&nbsp;FM or online via <a href="http://www.wrct.org">wrct.org</a>.</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Myth’s and Legends of Buggy Panel</h5>
    <h6 class="card-subtitle mb-2 text-muted">Thurs, April 19 @ 12:30pm</h6>
    <p class="card-text">Taking a page from the Carnival theme this year, a group of panelists across the generations will share their own buggy myths and legends during Design Showcase. Panelists to be announced.</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Welcome Back Happy Hour <span class="badge badge-primary text-uppercase">New Location</span></h5>
    <h6 class="card-subtitle mb-2 text-muted">Thurs, April 19 @ 7:30pm</h6>
    <p class="card-text">This year, our Welcome Back Happy Hour is moving to Fuel and Fuddle, the newest bar with a buggy! Come hang out with other early arrivals and share your Raceday 2018 predictions.</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Prelim Races</h5>
    <h6 class="card-subtitle mb-2 text-muted">Fri, April 20 @ 7:20am</h6>
    <p class="card-text">Come join us in person or online to watch prelims!</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">History of Buggy (‘93 edition) w/ Tom Wood</h5>
    <h6 class="card-subtitle mb-2 text-muted">Fri, April 20 @ 1:30pm</h6>
    <p class="card-text">Our regular can’t miss event is back as Tom Wood shares a history of buggy focused on the class of ‘93. His talk will be held in the Danforth Conference room in the CUC.</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Buggy Meetup and Finals Lead Truck Auction <span class="badge badge-primary text-uppercase">New Event</span></h5>
    <h6 class="card-subtitle mb-2 text-muted">Fri, April 20 @ 7:30pm</h6>
    <p class="card-text">For the first time ever, bid live on the finals heats’ lead truck rides <em>after</em> the heats have been decided, and stick around to share your Raceday experiences at Hough’s taproom, the original bar with a buggy!</p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Finals Races</h5>
    <h6 class="card-subtitle mb-2 text-muted">Sat, April 21 @ 8am</h6>
    <p class="card-text">Finals!</p>
  </div>
</div>
