<footer class="container text-center text-muted small py-4">
  <hr>
  <div class="row justify-content-around align-items-center py-2">
    <div>
      <h4><a href="/membership" class="btn btn-primary"><b>Join our Community</b></a></h4>

      <div class="my-3 text-center text-muted">
        <a href="https://www.facebook.com/pages/Carnegie-Mellon-Buggy-Alumni-Association/279568438094" style="text-decoration: none">
          <i class="fab fa-2x fa-fw fa-facebook-square" title="Facebook" style="color: #3b5998;"></i>
        </a>
        <a href="/chat" style="text-decoration: none">
          <span class="fa-layers fa-2x fa-fw">
            <i class="fas fa-square" style="color: #5865F2;"></i>
            <i class="fab fa-discord fa-inverse text-white" data-fa-transform="shrink-6" title="Discord"></i>
          </span>
        </a>
        <a href="/news/feed/" style="text-decoration: none">
          <i class="fas fa-2x fa-fw fa-rss-square" style="color: #f26522" title="Feed"></i>
        </a>
        <a href="https://twitter.com/CMUBuggy" style="text-decoration: none">
          <i class="fab fa-2x fa-fw fa-twitter-square" title="Twitter" style="color: #1da1f2;"></i>
        </a>
        <a href="https://instagram.com/cmubuggy" style="text-decoration: none">
          <i class="fab fa-2x fa-fw fa-instagram-square" title="Instagram" style="color: #e1306c;"></i>
        </a>
        <a href="https://www.youtube.com/user/CMUbuggy" style="text-decoration: none">
          <i class="fab fa-2x fa-fw fa-youtube-square" title="Youtube" style="color: #ff0000;"></i>
        </a>
        <a href="/spotify">
          <span class="fa-layers fa-2x fa-fw">
            <i class="fas fa-square" style="color: #1DB954;"></i>
            <i class="fab fa-spotify fa-inverse" title="Spotify" data-fa-transform="shrink-6"></i>
          </span>
        </a>
      </div>
    </div>
    <div>
      <ul class="list-unstyled">
        <li><a href="/about/get-involved">Volunteer / Get Involved</button></li>
        <li><a href="https://groups.google.com/g/baa-news">BAA News in your Inbox</a></li>
        <li><a href="https://groups.google.com/g/buggy-watchers">Buggy-Watchers Notification List</a></li>
      </ul>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="text-center">
      <span class="text-nowrap">CMU Buggy Alumni Association</span> &copy;2008&ndash;<?php echo date('Y'); ?><br>
      <a href="mailto:admin@cmubuggy.org">admin@cmubuggy.org</a>
      <hr width="50%">
      <i>While we are proud members of the CMU family, this website is managed by private individuals who are not employees of CMU.<br>
         Carnegie Mellon University has no role in the creation of this website or any of the content.</i>
    </div>
  </div>

</footer>
