<div id="googlesearch">
  <form action="/search" id="cse-search-box">
      <input type="hidden" name="cx" value="partner-pub-0853691456815687:qemwh6-hd6k" />
      <input type="hidden" name="cof" value="FORID:9" />
      <input type="hidden" name="ie" value="ISO-8859-1" />
      <input type="text" name="q" class="input" style="width:140px; margin:10px auto;"/>
      <input type="submit" name="sa" value="Search" class="button" />
  </form>
</div>
<script type="text/javascript" src="https://www.google.com/cse/brand?form=cse-search-box&amp;lang=en"></script>
