<div id="googlesearch">
  <form action="/search" id="cse-search-box">
    <input type="hidden" name="cx" value="partner-pub-0853691456815687:qemwh6-hd6k" />
    <input type="hidden" name="cof" value="FORID:9" />
    <input type="hidden" name="ie" value="ISO-8859-1" />
    <div class="input-group my-3">
      <input type="text" name="q" class="form-control" aria-label="search" />
      <div class="input-group-append">
        <button type="submit" name="sa" class="btn btn-outline-secondary" aria-label="search"><i class="fas fa-search"></i></button>
      </div>
    </div>
  </form>
</div>
<script type="text/javascript" src="https://www.google.com/cse/brand?form=cse-search-box&amp;lang=en"></script>
