    <div class="card mb-3">
      <h5 class="card-header">Raceday 2023 is <?php echo($timerSmallWord." ".$timerCount." ".$timerUnit); ?>!</h5>
      <div class="card-body">
        Spring Carnival will be here before you know it!  We're looking forward to seeing everyone again!
<?php
  // When volunteer links are raceday, set to true
  if (true) {
?>
        <p>
        <p>Watch this space for updates as raceday approaches.</p>
        <p>Our members help make raceday happen.  If you'll be in town, please sign up to help.
        You can sign up for <a href="/broadcast-volunteer">the broadcast</a> or
        <a href="/volunteer">many other roles</a>.</p>
<?php } ?>
      </div>
    </div>