<div id="homepage">
    <?php include_once("contentfeed.inc");   ?> 	 
    <div  class="yui3-g"  style="width:500px; height:145px;">
  		<div class="yui3-u-2-5">
			<?php include_once("freerollstatus.inc"); ?>			
		</div>
		<div class="yui3-u-3-5">
			<h3>Get Involved!</h3>
				<div class="item">
					<a href="/reference/">
						<div class="icon referenceicon">Reference<img src="img/icon_book.png"></div>
					</a>
					Wait, what is "buggy"??? <br /> Visit our <a href="/reference">Reference section</a> for a quick explanation, or <a href="/video" />watch some videos</a>.
				</div>
				<ul class="list">
					<li><a href="/leaderboard">2013 Official results</a></li>
					<li>Want to help out with <a href="/news/category/rolls-reports/" >rolls reports</a> this fall? E-mail committee@cmubuggy.org to get started.</li>		
				</ul>
		</div>
    </div>
    <?php include_once("featurepic.inc"); ?>
    <div class="pane clearleft" style="margin-right:270px;">
        <h3 style="margin:0">Buggy Alumni Association?</h3>
        We were founded in 2008 to unite and connect alumni across teams and eras, and to support the coolest sport we know.  Join us! We're open to everyone: current students, Pittsburgh locals, enthusiasts of any kind. Find out more in <a href="/about">About Us section ...</a>	
    </div>
    <div class="pane" style="margin-right:270px;">
        <h3 style="margin:0">Buggy?</h3>
        Buggy (also called "Sweepstakes") is a unique race that has been held on and behind the Carnegie Mellon University campus during the spring carnival since 1920.  It is part uphill relay race (in which the baton is a vehicle and driver pushed by runners), and part downhill gravity racing with exciting sharp turns and speeds up to 40mph. Find out more in the <a href="/reference/What_is_buggy%3F">What is Buggy? section ...</a>
    </div>
</div>