    <div class="card mb-3">
      <h5 class="card-header">Raceday 2022 is <?php echo($timerSmallWord." ".$timerCount." ".$timerUnit); ?>!</h5>
      <img class="card-img-top" src="<?php echo(makeSmugmugUrl("i-jZjxT8C")); ?>">
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <a href="/raceday" class="btn btn-primary m-1">Raceday Info Center</a>
          <a href="/live" class="btn btn-info m-1">Livestream</a>
          <a href="/chat" class="btn btn-info m-1">Chat</a>
        </div><div class="d-flex justify-content-center mb-2">
          <a href="/raceday/rosters" class="btn btn-secondary m-1">Rosters</a>
          <a href="/raceday/heats" class="btn btn-secondary m-1">Heats</a>
          <a href="/raceday/leaderboard" class="btn btn-secondary m-1">Leaderboard</a>
        </div>
        <p>Raceday 2022 is upon us! We're excited to see everyone and celebrate the 100th anniversary of Buggy!</p>
        <p>Our <a href="/raceday">raceday info center</a> is the place to go for everything you need to know about all in-person and virtual activites.</p>
        <p>Key Events:</p>
        <ul>
          <li>Design Showcase: Thursday Apr 7, 12pm-2pm</li>
          <li>Preliminary Races: Friday Apr 8, 8am-12pm</li>
          <li>Finals Races: Saturday Apr 9, 8am-12pm</li>
        </ul>
      </div>
    </div>