    <div class="card mb-3">
      <h5 class="card-header">Raceday 2023 is <?php echo($timerSmallWord." ".$timerCount." ".$timerUnit); ?>!</h5>
      <div class="card-body">
        Spring Carnival will be here before you know it!  We're looking forward to seeing everyone again!
<?php
  // When volunteer links are ready, set to true
  if (false) {
?>
        <p>
        <p>Watch this space for updates as raceday approaches.</p>
        <p>Our members help make raceday happen.  If you'll be in town, please sign up to help.</p>

        <a target="_blank" href="/volunteer" class="btn btn-primary">Help Us Out!</a>
        <a target="_blank" href="/broadcast-volunteer" class="btn btn-primary">Be A Commentator!</a>
<?php } ?>
      </div>
    </div>