<div id="homepage">
     <?php include_once("contentfeed.inc");   ?>     
        <div  class="yui3-g"  style="width:500px; height:145px;">
        <div class="yui3-u-3-5">
            <table class="datacompact" style="margin-top:0px;">
                <tr>
                    <th colspan="2"><h3 style="margin:0;"><a href="/history/raceday/2017/">2017 Results</a></h3></th>
                    <th colspan="1" style="text-align:right; font-size:1em;"><b>Men's</b></th>
                    <th colspan="2" style="text-align:right; font-size:1em;"><b>Women's</b></th>
                </tr>
                <tr>
                    <td><b>1<sup>st</sup></b></td>
                    <td>SDC A</td>
                    <td>2:02.16</td>
                    <td class="newcol">SDC A</td>
                    <td>2:23.27</td>
                </tr>
                <tr>
                    <td><b>2<sup>nd</sup></b></td>
                    <td>PiKA A</td>
                    <td>2:08.42</td>
                    <td class="newcol">SDC B</td>
                    <td>2:32.80</td>
                </tr>
                <tr>
                    <td><b>3<sup>rd</sup></b></td>
                    <td>SigEp A</td>
                    <td>2:09:24</td>
                    <td class="newcol">PiKA A</td>
                    <td>2:33.24</td>
                </tr>
                <tr>
                    <td colspan="5" style="font-size:12px;">Design: 1<sup>st</sup> Blueshift &ndash; Fringe, 2<sup>nd</sup> Equinox &ndash; CIA, 3<sup>rd</sup> Inviscid &ndash; Spirit</td>
                </tr>
                <tr>
                    <td colspan="3" style="font-size:11px;"><span style="font-size:11px;">People's Choice:</span> Inviscid &ndash; Spirit</td>
                    <td colspan="2" style="font-size:11px;"><span style="font-size:11px;">Spirit of Buggy:</span> Fringe</td>
                </tr>
                <tr>
                    <td colspan="3" style="font-size:11px;"><span style="font-size:11px;">Chairman's Choice</span>: SigEp</td>
                    <td colspan="2" style="font-size:11px;"><span style="font-size:11px;">TShirt</span>: SigNu</td>
                </tr>
                <tr>
                    <td colspan="5" style="font-size:11px;"><span style="font-size:11px;">Design Showcase Spark</span>: Beyonce &ndash; SigEp</td>
                </tr>
                <tr>
                    <td colspan="3" style="font-size:11px;"><span style="font-size:11px;">King of the Hill</span>: Jacob Hoffman &ndash; SDC A</td>
                    <td colspan="2" style="font-size:11px;"><span style="font-size:11px;">Queen of the Hill</span>: Mary Garrett &ndash; SDC A</td>
                </tr>
            </table>
        </div>
        <div class="yui3-u-2-5">
            <h3>Get Invloved</h3>
            <div class="item"><a href="/seniors"><div class="icon" style="background-image:url('/img/icon_grad-cap.png')"></div></a><a href="/seniors">Seniors!</a> Become a 2018 member now for free.</div>
            <div class="item">
                <a href="/gallery/2016-2018">
                    <div class="icon galleryicon" style="background-image:url('http://cmubuggy.org/gallery/var/resizes/2016-2017/Raceday---Finals/IMG_9891.JPG')"></div>
                </a>
                Share your favorite pics from
                <a href="/gallery/2016-2017/Raceday---Design-Showcase">Design</a>,
                <a href="/gallery/2016-2017/Raceday---Prelims">Prelims</a>,
                <a href="/gallery/2016-2017/Raceday---Finals">Finals</a>

            </div>
        </div>
    </div>
    <br />
    <?php include_once("twitterwidget.inc"); ?>
    <div class="pane clearleft" style="margin-right:270px;">
        <h3 style="margin:0">Buggy Alumni Association?</h3>
        We were founded in 2008 to unite and connect alumni across teams and eras, and to support the coolest sport we know.  Join us! We're open to everyone: current students, Pittsburgh locals, enthusiasts of any kind. Find out more in <a href="/about">About Us section ...</a> 
    </div>
    <div class="pane" style="margin-right:270px;">
        <h3 style="margin:0">Buggy?</h3>
        Buggy (also called "Sweepstakes") is a unique race that has been held on and behind the Carnegie Mellon University campus during the spring carnival since 1920.  It is part uphill relay race (in which the baton is a vehicle and driver pushed by runners), and part downhill gravity racing with exciting sharp turns and speeds up to 40mph. Find out more in the <a href="/reference/What_is_buggy%3F">What is Buggy? section ...</a>
    </div>
</div>
