<div class="box whitebox">

	You have successfully registered!  Please login using the login form on the left side of the page.  Please see below for information about becoming a dues paying member of the BAA.
</div>

<br style="clear:left;" />
<div class="box whitebox">
	<h3>Become a dues paying member</h3>
	Most of the services of the Buggy Alumni Association are available to everyone in the buggy and CMU community.  We want the hard work we have done collecting, organizing, and sharing the history of buggy to be enjoyed by all.  We also want everyone to benefit from stronger, broader participation in today's buggy races.<br />
	<br />
	<h3>Benefits of being a member</h3>
	<table class="data">
		<tr><th>Date</th><th>Benefit</th><th>Description</th></tr>
		<tr><td style="width:50px;">December</td><td>Fall Wrap-up</td><td>Summaries of each org's progress with interview comments from leaders of each org.</td></tr>
		<tr><td>Monday before Raceday</td><td>Raceday Preview</td><td>This in-depth coverage of the current state of the buggy world will get you back in the loop just in time to get the most out of raceday. To be sent to all dues-paying members on truck weekend. <br /><b><a onclick="javascript: pageTracker._trackPageview('/files/RacedayPreview2009.pdf');" href="/files/RacedayPreview2009.pdf">Download the 2009 edition as a preview</a></b></td></tr>
		<tr><td>Carnival Friday</td><td>Admission to the Raceday Reception</td><td>Eat, drink, and discuss the actions at prelims right next to hill 1.</td></tr>
		<tr><td>Late April</td><td>Raceday Wrap-up</td><td>Coverage of the races by folks that have been there. We'll break down performances by each team and cover all of the action.</td></tr>
		<tr><td>All year</td><td colspan="2">The satisfaction that you are helping to support the Buggy Alumni Association's mission</td></tr>
	</table>
	<br />
	Annual dues are processed through the CMU Alumni site, so click here to become a CMU Buggy Alumni Association 2010 Dues Paying Member<br />
	<div class="box" >
		<div class="title"><a href="https://www.alumniconnections.com/olc/pub/CMU/events/event_order.cgi?tmpl=events&event=2212486" target="_blank">Join</a></div>
	</div>
	All funds go directly to the CMU Buggy Alumni Association for administrative costs, member communications and Carnival and Homecoming events.  Membership dues are not tax deductible.
</div>
<div class="box whitebox">
	<div class="title">Make a gift to the Buggy Alumni Association</div>
	While the $10 annual dues allow us to operate and grow as an alumni organization, gifts empower the Buggy Alumni Association to persue projects that advance our goals of helping buggy thrive.  The specific projects that we are persuing are described in the <a href="/About">About Us</a> section of the site.
	<div class="box">
		<div class="title"><a href="https://www.cmu.edu/campaign/ways/online.html?designation=Buggy%20Alumni%20Association&PCH=A0661">Make a Gift</a></div>
	</div>
	This button will take you to the CMU giving site where you'll see on step 2 that the Buggy Alumni Association has been pre-selected as the designee. Thank you!
</div>
