<nav>
  <ul class="list-group my-3">
<?php
  // Enable each year as we launch the raceday info center.
  if (false) { ?>
    <li class="list-group-item"><a class="d-block" href="/raceday">Raceday</a></li>
<?php } ?>
    <li class="list-group-item"><a class="d-block" href="https://cmubuggy.smugmug.com" target="_blank">Photos</a></li>
    <li class="list-group-item"><a class="d-block" href="/history">Historical Data</a></li>
    <li class="list-group-item"><a class="d-block" href="/news">News</a></li>
    <li class="list-group-item"><a class="d-block" href="/reference">Reference</a></li>
    <li class="list-group-item"><a class="d-block" href="/membership">Membership</a></li>
    <li class="list-group-item"><a class="d-block" href="/about">About the BAA</a></li>
  </ul>
</nav>

<?php include("googlesearchinput.inc"); ?>

<div class="my-3 text-center text-muted">
  <a href="https://www.facebook.com/pages/Carnegie-Mellon-Buggy-Alumni-Association/279568438094" style="text-decoration: none">
    <i class="fab fa-2x fa-fw fa-facebook-square" title="Facebook" style="color: #3b5998;"></i>
  </a>
  <a href="/chat" style="text-decoration: none">
    <span class="fa-layers fa-2x fa-fw">
      <i class="fas fa-square" style="color: #5865F2;"></i>
      <i class="fab fa-discord fa-inverse" data-fa-transform="shrink-6" title="Discord"></i>
    </span>
  </a>
  <a href="/news/feed/" style="text-decoration: none">
    <i class="fas fa-2x fa-fw fa-rss-square" style="color: #f26522" title="Feed"></i>
  </a>
  <a href="https://twitter.com/CMUBuggy" style="text-decoration: none">
    <i class="fab fa-2x fa-fw fa-twitter-square" title="Twitter" style="color: #1da1f2;"></i>
  </a>
  <a href="https://instagram.com/cmubuggy" style="text-decoration: none">
    <i class="fab fa-2x fa-fw fa-instagram-square" title="Instagram" style="color: #e1306c;"></i>
  </a>
  <a href="https://www.youtube.com/user/CMUbuggy" style="text-decoration: none">
    <i class="fab fa-2x fa-fw fa-youtube-square" title="Youtube" style="color: #ff0000;"></i>
  </a>
  <a href="/spotify">
    <span class="fa-layers fa-2x fa-fw">
      <i class="fas fa-square" style="color: #1DB954;"></i>
      <i class="fab fa-spotify fa-inverse" title="Spotify" data-fa-transform="shrink-6"></i>
    </span>
  </a>
</div>
