<nav>
  <ul class="list-group my-3">
<?php
  // Enable each year as we launch the raceday info center.
  if (false) {
?>
    <li class="list-group-item d-block"><a href="/raceday">Raceday</a></li>
<?php } ?>
    <li class="list-group-item d-block text-nowrap">
        <a href="https://cmubuggy.smugmug.com" target="_blank">Photos</a> /
        <a href="/video">Videos</a>
    </li>
    <li class="list-group-item d-block"><a href="/history">Historical Data</a></li>
    <li class="list-group-item d-block"><a href="/news">News</a></li>
    <li class="list-group-item d-block"><a href="/reference">Reference</a></li>
    <li class="list-group-item d-block"><a href="/membership">Membership</a></li>
    <li class="list-group-item d-block"><a href="/about">About the BAA</a></li>
  </ul>
</nav>

