<div id="topnav">
	<ul class="sf-menu">
		<li><a href="/live" target="_blank">Live Streaming Broadcast</a></li>
		<li><a href="/buzz" target="_blank">Buzz (live chat)</a></li>
	</ul>
</div>
<div class="pane">
Live broadcasts are a new cmubuggy project.  Currently, we'll be be broadcasting some mornings of freerolls (roughly 7-9am).  <a href="http://www.ustream.tv/channel/freerolls-live">Recorded versions</a> will also be available for playback later.<br />
<br />
<iframe src="http://www.ustream.tv/embed/9728056" width="725" height="448" scrolling="no" frameborder="0" style="border: 0px none transparent;"></iframe>
Live streaming is currently broadcast through <a href="http://www.ustream.tv/channel/freerolls-live">USTREAM.tv</a>.
Join the <a href="/buzz" target="_blank">cmubuggy Buzz chat room</a> if you're watching and share your comments.
Are the ads super annoying?  It would cost <a href="https://secure-www.ustream.tv/ustream-pro?lang=en_US" target="_blank">about $500</a> to remove them (and broadcast in HD) for the year.  Let us know if you think that would be worthwhile (or any other ideas/improvements) in the <a href="http://www.reddit.com/r/cmubuggy/comments/m8db3/live_webcast_of_rolls/">Project Zone discussion on live broadcasts</a>.
</div>
