<nav class="navbar navbar-light navbar-expand bg-light mb-3">
  <ul class="navbar-nav flex-wrap">
    <li class="nav-item">
      <a class="nav-link" href="/raceday">Raceday Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/raceday/heats">Heat Schedule</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/history">Leaderboard</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" target="_blank" rel="noopener" href="https://discord.gg/PUwuUuj">Chat</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/live">Live</a>
    </li>
  </ul>
</nav>

<div class="embed-responsive embed-responsive-16by9 mb-3">
  <iframe id="kmsembed-1_14ngshpg" width="960" height="540" src="https://mediaservices.cmu.edu/embed/secure/iframe/entryId/1_14ngshpg/uiConfId/32384181" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>
</div>

<p>Join the <a href="/RD20" target="_blank" rel="noopener">Zoom webinar</a> and interact with the broadcast.</p>
