<nav class="navbar navbar-light navbar-expand bg-light mb-3">
  <ul class="navbar-nav flex-wrap">
    <li class="nav-item"><a class="nav-link" href="/live" target="_blank">Live Streaming Broadcast</a></li>
    <li class="nav-item"><a class="nav-link" href="/buzz" target="_blank">Buzz (live chat)</a></li>
  </ul>
</nav>

<p>Live broadcasts are a new cmubuggy project. Currently, we'll be be broadcasting some mornings of freerolls (roughly 7-9am). <a href="http://www.ustream.tv/channel/freerolls-live">Recorded versions</a> will also be available for playback later.</p>

<div class="embed-responsive embed-responsive-16by9 mb-3">
  <iframe src="https://www.ustream.tv/embed/9728056?html5ui" scrolling="no" allowfullscreen class="embed-responsive-item"></iframe>
</div>

<p>Live streaming is currently broadcast through <a href="http://www.ustream.tv/channel/freerolls-live">USTREAM.tv</a>. Join the <a href="/buzz" target="_blank">cmubuggy Buzz chat room</a> if you're watching and share your comments. Are the ads super annoying? It would cost <a href="https://secure-www.ustream.tv/ustream-pro?lang=en_US" target="_blank" rel="noopener">about $500</a> to remove them (and broadcast in HD) for the year. Let us know if you think that would be worthwhile (or any other ideas/improvements) in the <a href="http://www.reddit.com/r/cmubuggy/comments/m8db3/live_webcast_of_rolls/">Project Zone discussion on live broadcasts</a>.</p>
