<ul class="nav <?php echo("$nav_class"); ?>">
  <!-- TODO: Active tab, better styles -->
  <li class="nav-item">
    <a class="nav-link text-dark" href="/news">News</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark" href="/reference">What is Buggy?</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark " href="/history">History</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark" href="/about">About the BAA</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark" href="https://cmubuggy.smugmug.com" target="_blank">Gallery</a>
  </li>
</ul>