<h1>Join us, Seniors!</h1>

<p>The Buggy Alumni Association would like to congratulate all of the graduating seniors for a great raceday, and welcome you to join the fastest growing buggy-oriented alumni association in the world.</p>

<p>If you think the post-raceday withdrawal is bad now, just wait until next year when you are stuck at work wondering what's going on at rolls. Don't worry, we've got you covered.</p>

<p>Just fill out this form, and you'll get 1 year in the exclusive club of supporting members at no cost to you. More details on membership, who's a member, and what it means in <a href="/membership">the membership section</a>.</p>

<iframe src="https://spreadsheets.google.com/embeddedform?key=pbjqurVOBSn77awvmpxALHw" width="675" height="1300" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
