<a class="twitter-timeline"
   width="500"
   height="400"
   data-chrome="noheader nofooter"
   href="https://twitter.com/CMUBuggy"
   data-widget-id="454018447379161088">Tweets by @CMUBuggy</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
