<iframe width='750' height='1150' frameborder='0' src='https://docs.google.com/spreadsheet/pub?key=0AuJqrzitvsWSdHhfbkpoWVg3V2lOclItelJ2d1JNdlE&output=html'></iframe>
Also check out last year's time's if you need a refresher since they aren't (yet) in our official cmubuggy.org history database:<br />
<a href="https://docs.google.com/spreadsheet/pub?key=0AuJqrzitvsWSdFVRY0dqeDhWOW42Y3RSNDBzSTBrZGc&output=html">2012 Raceday Times</a> 
