<h1>Raceday Survival Tools</h1>

<div class="row">
  <div class="media mb-3 col-md-6">
    <img src="/img/cmutvlogo.gif" alt="cmuTV logo" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a target="_blank" rel="noopener" href="http://new.livestream.com/cmuTVlive">cmuTV</a></h5>
      cmuTV will be producing live coverage and streaming it online viewable right in your browser with no additional set-up. Check their site Friday morning for the link.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/wrctlogo.gif" alt="WRTC logo" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a target="_blank" rel="noopener" href="http://wrct.org/">WRCT</a></h5>
      WRCT will be broadcasting the live audio coverage from loudspeakers on the course, 88.3 FM locally, and online from wrct.org
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/leaderboard.jpg" alt="leaderboard" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/raceday/leaderboard">Leaderboard</a></h5>
      It's tough to keep the whole top 10 in your head. Check here for instantaneous updates entered directly by the head timer.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/icon_sunrise.png" alt="sunrise" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/raceday/heats">Heat Schedule</a></h5>
      Don't miss your team because you forgot the schedule.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/chaticon.png" alt="chat" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="https://discord.gg/PUwuUuj">Chat</a></h5>
      We know there are alumni all over the world watching and listening to the coverage that would love to communicate faster than the forum will allow. We bring you the Raceday Chat.
    </div>
  </div>
</div>
