<div class="pane">
    <h3>Survival Tools</h3>
    <table class="aligntop padded">
        <tr>
            <td style="width:50px"><a target="_blank" href="http://new.livestream.com/cmuTVlive"><img src="/img/cmutvlogo.gif" /></a></td>
            <td style="width:250px"><a target="_blank" href="http://new.livestream.com/cmuTVlive"><b>cmuTV</b></a> will be producing live coverage and streaming it online viewable right in your browser with no additional set-up.  Check their site Friday morning for the link.<br /></td>
            <td style="width:50px"><a target="_blank" href="http://wrct.org/"><img src="/img/wrctlogo.gif" /></a></td>
            <td style="width:250px"><a target="_blank" href="http://wrct.org/"><b>WRCT</b></a> will be broadcasting the live audio coverage from loudspeakers on the course, 88.3 FM locally, and online from wrct.org<br /></td>
        </tr>
        <tr>
            <td><a href="/raceday/leaderboard"><img src="/img/leaderboard.jpg" /></a></td>
            <td><a href="/raceday/leaderboard"><b>Leaderboard</b></a> - It's tough to keep the whole top 10 in your head.  Check here for instantaneous updates entered directly by the head timer<br /></td>
            <td><a href="/raceday/heats"><img src="/img/icon_sunrise.png" /></a></td>
            <td><a href="/raceday/heats"><b>Heat Schedule</b></a> - Don't miss your team because you forgot the schedule.<br /></td>
        </tr>
        <tr>
            <td><a href="https://discord.gg/PUwuUuj"><img src="/img/chaticon.png" /></a></td>
            <td><a href="https://discord.gg/PUwuUuj"><b>Chat</b></a> - We know there are alumni all over the world watching and listening to the coverage that would love to communicate faster than the forum will allow.  We bring you the Raceday Chat.<br /></td>
            <td>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="50">
                <path d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"/>
              </svg>
              <!-- svg from Font Awesome - https://fontawesome.com/license -->
            </td>
            <td>
              <a href="/events"><b>Events</b></a> - Check out our full list events for Carnival 2018.
            </td>
        </tr>
    </table>
</div>
