<h1>Raceday Survival Tools</h1>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Streaming Schedule for Saturday, April 18</h5>
    <ul class="mb-0">
      <li><b>Noon:</b> Opening remarks from Gina Casalegno</li>
      <li><b>Noon - 1:30pm:</b> 2003-2015 Raceday Highlights w/ Commentary</li>
      <li><b>1:30pm - 2:15pm:</b> BAA Student and Alumni Panel</li>
      <li><b>2:15pm - 3:00pm:</b> 2016-2018 Raceday Highlights & Buggy Graduate Recognition</li>
      <li><b>3:00pm - 3:20pm:</b> Trivia Speed Round</li>
      <li><b>3:20pm - 3:25pm:</b> 2019 Raceday Highlights</li>
      <li><b>3:25pm:</b> Closing message from Sweepstakes & BAA</li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="media mb-3 col-md-6">
    <img src="/img/cmutvlogo.gif" alt="cmuTV logo" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/live">Livestream</a></h5>
      Go check out this year's livestream!
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/wrctlogo.gif" alt="WRTC logo" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a target="_blank" rel="noopener" href="http://wrct.org/">WRCT</a></h5>
      WRCT will be broadcasting some buggy panels
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/leaderboard.jpg" alt="leaderboard" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/history">Leaderboard</a></h5>
      It's tough to keep the whole top 10 in your head. Check here for instantaneous updates entered directly by the head timer.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/icon_sunrise.png" alt="sunrise" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/raceday/heats">Heat Schedule</a></h5>
      Don't miss your team because you forgot the schedule.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/chaticon.png" alt="chat" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a target="_blank" href="https://discord.gg/PUwuUuj">Chat</a></h5>
      We know there are alumni all over the world watching and listening to the coverage that would love to communicate faster than the forum will allow. We bring you the Raceday Chat.
    </div>
  </div>
  <div class="media mb-3 col-md-6">
    <img src="/img/logo-square-small.png" alt="BAA logo" class="mr-3 raceday-thumb">
    <div class="media-body">
      <h5 class="mt-0"><a href="/img/broadcast-bingo.pdf" download>Broadcast Bingo</a></h5>
      Play bingo during the broadcast
    </div>
  </div>
</div>
