<h1 class="sr-only">Admin Home</h1>
<h2>Edit content</h2>
<ul>
  <li><a href="/admin/members" >Members</a></li>
</ul>
<h2>Admin Links</h2>
<ul>
  <li><a href="/news/wp-admin" >News Section: Post, edit, manage</a></li>
  <li><a href="https://docs.google.com/document/d/18ZbgiqiOmEJXiZDmPrJxfu7dJTp5rbDI9HBCyCjtA4Y/edit?hl=en_US" >BAA Account Details</li>
  <li><a href="https://www.google.com/analytics/" >Google Analytics</li>
</ul>
