use cmubuggy_auction;
delete from auctions;
insert into auctions values (0,1,'SPIRIT-B','SIGEP-D','CIA-D','10:1','m',1);
insert into auctions values (0,2,'FRINGE-B','PIKA-D','SIGEP-C','10:2','m',1);
insert into auctions values (0,3,'SDC-C','SPIRIT-C','SAE-A','10:3','m',1);
insert into auctions values (0,4,'PIKA-B','CIA-B','SPIRIT-D','10:4','m',1);
insert into auctions values (0,5,'SDC-B','FRINGE-C','AEPI-B','10:5','m',1);
insert into auctions values (0,6,'SIGEP-A','PIKA-C','CIA-C','10:6','m',1);
insert into auctions values (0,7,'SPIRIT-A','KAPSIG-A','EMPTY','10:7','m',1);
insert into auctions values (0,8,'PIKA-A','SDC-D','PIONEERS-A','10:8','m',1);
insert into auctions values (0,9,'FRINGE-A','SIGNU-A','AEPI-A','10:9','m',1);
insert into auctions values (0,10,'SDC-A','CIA-A','SIGEP-B','10:10','m',1);
insert into auctions values (0,1,'SDC-D','CIA-C','EMPTY','10:1','w',1);
insert into auctions values (0,2,'PIONEERS-A','PIKA-C','FRINGE-B','10:2','w',1);
insert into auctions values (0,3,'SPIRIT-A','SDC-C','CIA-B','10:3','w',1);
insert into auctions values (0,4,'PIKA-A','SIGEP-B','FRINGE-C','10:4','w',1);
insert into auctions values (0,5,'SDC-B','CIA-A','AEPI-A','10:5','w',1);
insert into auctions values (0,6,'FRINGE-A',' SAE-A',' SPIRIT-B','10:6','w',1);
insert into auctions values (0,7,'SDC-A',' PIKA-B',' SIGEP-A','10:7','w',1);
insert into auctions values (0,-1,'???','???','???','10 8','m',2);
insert into auctions values (0,-1,'???','???','???','10:8','w',2);
