<?php
	include "configuration.php";
	include "objects/class.pog_base.php";
	include "objects/class.database.php";
	include "objects/class.dataedit.php";
	include "objects/class.awardType.php";
	include "objects/class.broadcasterq.php";
	include "objects/class.buggy.php";
	include "objects/class.buggyAward.php";
	include "objects/class.dq.php";
	include "objects/class.entry.php";
	include "objects/class.freeroll.php";
	include "objects/class.heat.php";
	include "objects/class.member.php";
	include "objects/class.note.php";
	include "objects/class.org.php";
	include "objects/class.orgAward.php";
	include "objects/class.person.php";
	include "objects/class.personToOrg.php";
	include "objects/class.personToTeam.php";
	include "objects/class.raceclass.php";
	include "objects/class.raceday.php";
	include "objects/class.raceyear.php";
	include "objects/class.role.php";
	include "objects/class.sweepstakes.php";
	include "objects/class.sweepstakesRole.php";
	include "objects/class.team.php";
	include "objects/class.teamRole.php";
	include "objects/class.user.php";
	include "objects/class.video.php";
	include "objects/class.videogroup.php";



	//include "objects/class.oldteam.php";

?>
